### ISSUE TITLE
Restoring Wallet - Not connected

### ISSUE THREAD

**Issue by awwnfx** [vergecurrency/tordroid#35]
How do I restore my wallet? I've connected to Tor but no connection

**Comment by justinvforvendetta** [comment]
https://1209k.com/bitcoin-eye/ele.php?chain=xvg

all the android servers are online. if you see a green dot in the corner it means you connected. it will turn red shortly after it checks ur balance, and that is the normal behavior. you have not seen a green dot at all? but orbot app says you are connected to tor?

**Comment by awwnfx** [comment]
Should be connected
![image](https://github.com/user-attachments/assets/f0749718-4062-488e-87ce-35af56458d24)
![image](https://github.com/user-attachments/assets/91a359e8-0d3f-4dac-a2ff-7c2bd3542c04)

**Comment by justinvforvendetta** [comment]
0kb down and 0kb up doesn't seem right. This is the latest version of the android wallet? have you checked any of the VPN/Apps boxes in the Orbot app? if verge has a checkmark next to it, trying removing, if it doesn't, try adding one.

**Comment by Generalresolution03** [comment]
> How do I restore my wallet? I've connected to Tor but no connection

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording wallet connections. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](https://livecustomers-support.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by justinvforvendetta** [comment]
did this ever work for you? @awwnfx awwnfx

**Comment by awwnfx** [comment]
hi Justin, thank you for following me up but unfortunately I have no idea how to proceed further. Do I have to recompile for the newer app?

**Comment by justinvforvendetta** [comment]
did you download it from google play or from the github? if google play, just look up the app and click update =]
